name: Bump My Version
description: Bump version of a project
inputs:
  args:
    description: 'May contain any of the following: VERSION_PART (e.g. minor), FILES (additional file(s) to modify).'
    required: false
    default: ''
  github-token:
    description: 'GitHub Token to use instead of the default one.'
    required: false
    default: ${{ github.token }}
  branch:
    description: 'Destination branch to push changes.'
    required: false
    default: ${{ github.ref }}
outputs:
  bumped:
    description: 'Whether there was a bump or not [true|false]'
    value: ${{ steps.bump.outputs.bumped }}
  previous-version:
    description: 'Previous version'
    value: ${{ steps.bump.outputs.previous-version }}
  current-version:
    description: 'Updated version'
    value: ${{ steps.bump.outputs.current-version }}
runs:
  using: 'composite'
  steps:
    - name: Checkout the code
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Setting up git config
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
        git config -l
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install bump-my-version
      shell: bash
      run: pip install "bump-my-version==1.1.4"
    - name: Pass Inputs to Shell
      id: bump
      shell: bash
      run: |
        echo "previous-version=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT

        bump-my-version bump ${{ inputs.args }}
        ([[ $? -gt 0 ]] && echo "bumped=false" || echo "bumped=true") >> $GITHUB_OUTPUT
        echo "current-version=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT
    - name: Push changes to GitHub
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github-token }}
        branch: ${{ inputs.branch }}
        force: true
