site_name: Bump My Version
repo_url: https://github.com/callowayproject/bump-my-version
edit_uri: edit/master/docs/
copyright: Calloway Project
watch:
  - overrides
theme:
  name: material
  custom_dir: overrides
  logo: assets/bump-my-version-logo.svg
  favicon: assets/favicon.png
  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.tabs.link
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
use_directory_urls: true
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - customblocks
  - def_list
  - footnotes
  - md_in_html
  - mdx_truly_sane_lists
  - mkdocs-click
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - smarty
  - toc:
      permalink: true
      toc_depth: 3
  - tables

plugins:
  - search
  - git-revision-date-localized
  - git-authors:
      show_email_address: false
      exclude:
        - reference/api/*
  - include-markdown
  - drawio
  - literate-nav:
      nav_file: nav.md
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - mkdocstrings:
      custom_templates: overrides/mkdocstrings
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
            - https://api.python.langchain.com/en/latest/objects.inv
          options:
            allow_inspection: true
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: spacy
            group_by_category: true
            members_order: alphabetical
            merge_init_into_class: true
            separate_signature: true
            show_docstring_parameters: true
            show_root_toc_entry: true
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_category_heading: true

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"

extra_css:
  - assets/css/custom.css
  - assets/css/mkdocstrings.css
  - assets/css/cards.css
  - assets/css/field-list.css

nav:
  - Home: "index.md"
  - Tutorials: "tutorials/"
  - How Tos: "howtos/"
  - Reference: "reference/"
  - Explanation: "explanation/"
  - "CHANGELOG.md"
  - "CONTRIBUTING.md"
