name: Deploy final documentation

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      pages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Python and Git
        uses: ./.github/actions/setup-python-and-git
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          git pull --all
          uv sync -p 3.12 --group docs

      - name: Build and deploy documentation
        run: |
          uv run mkdocs gh-deploy --strict
